name: Deploy to workspace
on: [pull_request]
jobs:
  Deploy-Asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40.2.2
        with:
          separator: ","
          quotepath: false
      - name: Power BI Workspace Deploy
        uses: mahilario-arch/Power-BI-Workspace-Deploy@latest
        with:
          files: ${{ steps.changed-files.outputs.all_modified_files }}
          separator: ","
          tenant_id: "441d4a8f-7999-4d6a-9670-672cf8d03e35"
          config_file: ".github/config/workspace-deploy-config.yaml"
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
